### ISSUE TITLE
How to convert other classes such as road?

### ISSUE THREAD

**Issue by zhengjie6** [TillBeemelmanns/cityscapes_to_coco#1]
Hello, I am doing segmentation for road and would like to know how to convert the cityscapes dataset to coco for road segmentation. Thanks in advance.

**Comment by TillBeemelmanns** [comment]
You could adapt this list here to your needs. Only the classes in that list are being converted.

https://github.com/TillBeemelmanns/cityscapes-to-coco-conversion/blob/master/main.py#L137

```
category_instancesonly = [
        'person',
        'rider',
        'car',
        'truck',
        'bus',
        'train',
        'motorcycle',
        'bicycle',
    ]
```

**Comment by zhengjie6** [comment]
Understood. Thank you!

**Comment by hoominchu** [comment]
@zhengjie6 were you able to convert the 'road' class?
