### ISSUE TITLE
Does this work for gtBbox3d ?

### ISSUE THREAD

**Issue by Juphex** [TillBeemelmanns/cityscapes_to_coco#10]
I assume that this doesn't work for the gtBbox3d labels, right?
Is there any easy way for doing this?

Other than that, would it be good to add this here as a "feature"?

Best

**Comment by TillBeemelmanns** [comment]
Hi,

no unfortunately Cityscapes 3D is not supported. Cityscapes 3D is not being used very often in research as nuScenes and Waymo offer datasets with a much higher number of samples.

Actually, I am not sure what you want to do with the gtBbox3d labels? This repo will create 2D instance segmentations in COCO format. Correct me if I am wrong, but I don't think you can extend COCO with 3D information.

Bests,
Till

**Comment by Juphex** [comment]
Hi,

I was also curious because I was working with this repository and they used a a kitti to coco conversion, presumably for 3D bboxes. https://github.com/jizefeng0810/SDA-OD/blob/master/src/tools/convert_kitti_to_coco.py

Thank you for your answer, I guess I will not continue on trying to use COCO for 3d

**Comment by TillBeemelmanns** [comment]
My understanding of this script https://github.com/jizefeng0810/SDA-OD/blob/master/src/tools/convert_kitti_to_coco.py is that they project the 3D box onto the image plane obtaining 2D boxes and then converting it to COCO format. See function `_bbox_to_coco_bbox`. Hence, it is also generating 2D objects in COCO format. 

Bests, 
Till
