### ISSUE TITLE
Warning: invalid contours

### ISSUE THREAD

**Issue by JunsukLee** [TillBeemelmanns/cityscapes_to_coco#3]
This project works. But I'm curious what the following message means. Could you tell me, please?
"Warning: invalid contours."

**Comment by tarun005** [comment]
Same here. Did you figure out what this means? Does the json file have all the instances or are some skipped?

**Comment by YangYangGirl** [comment]
Same here. Did you figure out what this means? Does the json file have all the instances or are some skipped?

**Comment by DishantMewada** [comment]
If you check the main.py, you will find some contours are skipped if it is empty or if the size is very small.
```
for obj in objects[object_cls]:
    if obj['contours'] == []:
    print('Warning: empty contours.')
    continue  # skip non-instance categories
len_p = [len(p) for p in obj['contours']]
    if min(len_p) <= 4:
    print('Warning: invalid contours.')
    continue  # skip non-instance categories
```
so for classes like 'traffic light' or 'traffic sign' since len_p is very small it will be skipped. 
just comment out the last three lines in the code snippets and it will work.

**Comment by TillBeemelmanns** [comment]
Yes. This part filters out too small instances. Either change the threshold  `4` to a lower number or comment out these lines. You will need to check manually if these small instances make sense for your use case.
