### ISSUE TITLE
how can i get the pixels that belongs to a specific instance in the image ?

### ISSUE THREAD

**Issue by sasoyiano** [TillBeemelmanns/cityscapes_to_coco#6]
hi , thank you for the great work !
I'm beginner in computer vision 
how can i get the pixels that belongs to a specific instance in the image ?
i wanted to mask out the instance from the original image  :
https://tillbeemelmanns.github.io/assets/images/convert-cityscapes-to-coco/preview.png
to this : https://i.ibb.co/g4XQfv1/city-to-coco-1.jpg
all pixels that inside the mask 
and this : https://i.ibb.co/s5GyH7v/city-to-coco-2.jpg
all the pixel that is inside the bounding box 
is there anyway to extract these pixel directly from the instances id ?
Thanks in advance.

**Comment by TillBeemelmanns** [comment]
You wont need this tool to do that. You just need the camera image and the instance mask. Then you could read both of them into numpy arrays and do something like that

```
instance_id = 100
image[instance_mask == instance_id]
```
Then you would get the pixel values of that instance. Strongly suggest you to do a tutorial on numpy.
