### ISSUE TITLE
How to convert to other classes (ex: traffic light, traffic signs)

### ISSUE THREAD

**Issue by MarceloContreras** [TillBeemelmanns/cityscapes_to_coco#7]
Has somebody successfully converted cityscapes dataset filtering classes such as traffic lights, poles, etc? Indeed, I did the change of desired classes in `category_instancesonly` and also commented on the _invalid contour warning_. However, even if I did that, I still get .json output files with 0 annotations.

**Comment by aitor-martinez-seras** [comment]
The problem is that ```instanceIds``` images, where the different instances are labeled, do not have the labels for traffic lights, traffic signs, etc... They only have the categories used in this repo. Therefore it is not possible to extract those classes' ground truth for 2d bboxes.

**Comment by TillBeemelmanns** [comment]
The annotated classes in Cityscapes are shown here https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py#L88

As already pointed out. Traffic light and traffic signs do not have instance annotations.
