### ISSUE TITLE
Why does this script convert only instance objects? What is required to convert classes such as 'road' and 'sidewalk'?

### ISSUE THREAD

**Issue by hoominchu** [TillBeemelmanns/cityscapes_to_coco#9]

**Comment by TillBeemelmanns** [comment]
Cityscapes provides instance annotations only for some specific classes, as shown here in this definition 

https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py#L88

Other classes do not have instance annotations and are skipped in the script https://github.com/TillBeemelmanns/cityscapes-to-coco-conversion/blob/master/main.py#L76

What do you want to do ? Panoptic Segmentation ?

**Comment by hoominchu** [comment]
Yes, I went through the whole flow and say that non instance classes are being skipped by design. 

Right, I want to be able to do panoptic. Is there a way to do it? 

Thank you!

**Comment by TillBeemelmanns** [comment]
I think there is no need for you to use this script. You can use an open-source implementation of an PS approach, such as EfficientPS:
https://github.com/DeepSceneSeg/EfficientPS

They provide a script to preprocess the cityscapes dataset for PS
https://github.com/DeepSceneSeg/EfficientPS#prepare-datasets

Bests, 
Till

**Comment by hoominchu** [comment]
Thanks, will check it out!

**Comment by hoominchu** [comment]
Still curious, how easy/complicated is it to get this script working for panoptic?

**Comment by TillBeemelmanns** [comment]
It depends on your network architecture and loss function of the PS approach. Impossible to tell.

**Comment by hoominchu** [comment]
I intend to convert the cityscapes dataset into yolov8 format.
